# Generated by Django 3.1.7 on 2021-03-20 05:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 20, 5, 39, 6, 903505, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='journal',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 20, 5, 39, 6, 903505, tzinfo=utc)),
        ),
    ]
